// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;


		/// <content>
		/// Contains extern methods from "Gdi32.dll".
		/// </content>
	internal static partial class PInvoke
	{
		/// <summary>The DeleteObject function deletes a logical pen, brush, font, bitmap, region, or palette, freeing all system resources associated with the object. After the object is deleted, the specified handle is no longer valid.</summary>
		/// <param name="ho">A handle to a logical pen, brush, font, bitmap, region, or palette.</param>
		/// <returns>
		 /// <para>If the function succeeds, the return value is nonzero. If the specified handle is not valid or is currently selected into a DC, the return value is zero.</para>
		/// </returns>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wingdi/nf-wingdi-deleteobject">Learn more about this API from docs.microsoft.com.</see></para>
		/// </remarks>
		[DllImport("Gdi32", ExactSpelling = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)][SupportedOSPlatform("windows5.0")]internal static extern win32.Foundation.BOOL DeleteObject(win32.Graphics.Gdi.HGDIOBJ ho);

		/// <inheritdoc cref= "CreateSolidBrush(uint )"/>
		[SupportedOSPlatform("windows5.0")]internal static unsafe DeleteObjectSafeHandle CreateSolidBrush_SafeHandle(uint color)
		{
win32.Graphics.Gdi.HBRUSH __result = PInvoke.CreateSolidBrush(color);
			return new DeleteObjectSafeHandle(__result,ownsHandle: true);
		}

		/// <summary>The CreateSolidBrush function creates a logical brush that has the specified solid color.</summary>
		/// <param name="color">The color of the brush. To create a <a href="https://docs.microsoft.com/windows/desktop/gdi/colorref">COLORREF</a> color value, use the <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/nf-wingdi-rgb">RGB</a> macro.</param>
		/// <returns>
		 /// <para>If the function succeeds, the return value identifies a logical brush. If the function fails, the return value is <b>NULL</b>.</para>
		/// </returns>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wingdi/nf-wingdi-createsolidbrush">Learn more about this API from docs.microsoft.com.</see></para>
		/// </remarks>
		[DllImport("Gdi32", ExactSpelling = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)][SupportedOSPlatform("windows5.0")]internal static extern win32.Graphics.Gdi.HBRUSH CreateSolidBrush(uint color);
	}
}
