// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;

	namespace UI.WindowsAndMessaging
	{
		[Flags()]internal enum SHOW_WINDOW_CMD
:uint		{
SW_FORCEMINIMIZE = 0x0000000B,SW_HIDE = 0x00000000,SW_MAXIMIZE = 0x00000003,SW_MINIMIZE = 0x00000006,SW_RESTORE = 0x00000009,SW_SHOW = 0x00000005,SW_SHOWDEFAULT = 0x0000000A,SW_SHOWMAXIMIZED = 0x00000003,SW_SHOWMINIMIZED = 0x00000002,SW_SHOWMINNOACTIVE = 0x00000007,SW_SHOWNA = 0x00000008,SW_SHOWNOACTIVATE = 0x00000004,SW_SHOWNORMAL = 0x00000001,SW_NORMAL = 0x00000001,SW_MAX = 0x0000000B,SW_PARENTCLOSING = 0x00000001,SW_OTHERZOOM = 0x00000002,SW_PARENTOPENING = 0x00000003,SW_OTHERUNZOOM = 0x00000004,SW_SCROLLCHILDREN = 0x00000001,SW_INVALIDATE = 0x00000002,SW_ERASE = 0x00000004,SW_SMOOTHSCROLL = 0x00000010,		}
	}
}
