// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;

	namespace UI.WindowsAndMessaging
	{
		internal enum SYS_COLOR_INDEX
:uint		{
COLOR_3DDKSHADOW = 21U,COLOR_3DFACE = 15U,COLOR_3DHIGHLIGHT = 20U,COLOR_3DHILIGHT = 20U,COLOR_3DLIGHT = 22U,COLOR_3DSHADOW = 16U,COLOR_ACTIVEBORDER = 10U,COLOR_ACTIVECAPTION = 2U,COLOR_APPWORKSPACE = 12U,COLOR_BACKGROUND = 1U,COLOR_BTNFACE = 15U,_COLOR_BTNHIGHLIGHT = 20U,_COLOR_BTNHILIGHT = 20U,COLOR_BTNSHADOW = 16U,COLOR_BTNTEXT = 18U,COLOR_CAPTIONTEXT = 9U,COLOR_DESKTOP = 1U,COLOR_GRADIENTACTIVECAPTION = 27U,COLOR_GRADIENTINACTIVECAPTION = 28U,COLOR_GRAYTEXT = 17U,COLOR_HIGHLIGHT = 13U,COLOR_HIGHLIGHTTEXT = 14U,COLOR_HOTLIGHT = 26U,COLOR_INACTIVEBORDER = 11U,COLOR_INACTIVECAPTION = 3U,COLOR_INACTIVECAPTIONTEXT = 19U,COLOR_INFOBK = 24U,COLOR_INFOTEXT = 23U,COLOR_MENU = 4U,COLOR_MENUHILIGHT = 29U,COLOR_MENUBAR = 30U,COLOR_MENUTEXT = 7U,COLOR_SCROLLBAR = 0U,COLOR_WINDOW = 5U,COLOR_WINDOWFRAME = 6U,COLOR_WINDOWTEXT = 8U,		}
	}
}
