// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;

	namespace UI.WindowsAndMessaging
	{
		[Flags()]internal enum WINDOW_STYLE
:uint		{
WS_OVERLAPPED = 0x00000000,WS_POPUP = 0x80000000,WS_CHILD = 0x40000000,WS_MINIMIZE = 0x20000000,WS_VISIBLE = 0x10000000,WS_DISABLED = 0x08000000,WS_CLIPSIBLINGS = 0x04000000,WS_CLIPCHILDREN = 0x02000000,WS_MAXIMIZE = 0x01000000,WS_CAPTION = 0x00C00000,WS_BORDER = 0x00800000,WS_DLGFRAME = 0x00400000,WS_VSCROLL = 0x00200000,WS_HSCROLL = 0x00100000,WS_SYSMENU = 0x00080000,WS_THICKFRAME = 0x00040000,WS_GROUP = 0x00020000,WS_TABSTOP = 0x00010000,WS_MINIMIZEBOX = 0x00020000,WS_MAXIMIZEBOX = 0x00010000,WS_TILED = 0x00000000,WS_ICONIC = 0x20000000,WS_SIZEBOX = 0x00040000,WS_TILEDWINDOW = 0x00CF0000,WS_OVERLAPPEDWINDOW = 0x00CF0000,WS_POPUPWINDOW = 0x80880000,WS_CHILDWINDOW = 0x40000000,WS_ACTIVECAPTION = 0x00000001,		}
	}
}
