// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;

	namespace UI.WindowsAndMessaging
	{
		[Flags()]internal enum WNDCLASS_STYLES
:uint		{
CS_VREDRAW = 0x00000001,CS_HREDRAW = 0x00000002,CS_DBLCLKS = 0x00000008,CS_OWNDC = 0x00000020,CS_CLASSDC = 0x00000040,CS_PARENTDC = 0x00000080,CS_NOCLOSE = 0x00000200,CS_SAVEBITS = 0x00000800,CS_BYTEALIGNCLIENT = 0x00001000,CS_BYTEALIGNWINDOW = 0x00002000,CS_GLOBALCLASS = 0x00004000,CS_IME = 0x00010000,CS_DROPSHADOW = 0x00020000,		}
	}
}
